### PR TITLE
Design tweaks

### PR DESCRIPTION
**Pull request by leppert**
I took a quick stab at reworking the design. If you like it, let me know and I'll fix the obvious problems and push them to this branch. If it's not your cup of tea or you're not interested in making a change, no hard feelings.

screen shot 2016-10-16 at 4 53 49 pm

screen shot 2016-10-16 at 4 54 04 pm

screen shot 2016-10-16 at 4 54 08 pm

### CODE REVIEW

**Comment by yogthos** [comment]
I definitely think this is an improvement. The main page definitely pops out better with the new design. I'm also partial to the logo, it's simpler and cleaner than the one I came up with. :)

I did kinda like the terminal look for the quick start, but then again I'm not a designer. If you think it looks better just plain, I'm up for changing that.

**Comment by lacarmen** [comment]
I like the new home page as well (although the blue is a bit intense) but I also did like the terminal look for the quick start. 

I find the documentation pages a bit too empty. I prefer the style of the current site as it seems a little more lively - it's not so stark white. I think if you could combine the two designs or do some tweaking on the current one then it could look really nice.

**Comment by leppert** [comment]
@yogthos Pushed tweaks to make it work well enough on mobile so it should be good to go. Attached is an SVG file of the icon.
[logo.svg.zip](https://github.com/luminus-framework/luminus/files/532352/logo.svg.zip)

@lacarmen I agree, the blue is a bit intense. It's a bit different after these recent commits (give it a look), but still rather bold. That's my taste, but you two should feel free to tweak the color (or the docs layout) to your own taste if you like.

**Comment by yogthos** [comment]
👍 looks good, I'll merge it in and tinker a bit, and feel free to do another pr if you like. Thanks again for taking the initiative on this.

**Pull request merged**
