### PR TITLE
Fix setup docs

### PR DESCRIPTION
**Pull request by alexnixon**
`:source-map` must be a boolean when `:optimizations` is `:none`

### CODE REVIEW

**Comment by alexnixon** [comment]
I just realised there also seems to be a newer version of these docs :(

This was the top hit on Google for "luminus add cljs".

**Comment by yogthos** [comment]
ah I guess it cached the old docs?

**Comment by alexnixon** [comment]
No, the docs that Google took me to (that this PR was for) are in the file `resources/docs-1.x/clojurescript.md`.

But it looks like the docs which power the website (which is what I should have been reading) are in `resources/md/clojurescript.md`.

**Comment by yogthos** [comment]
ah gotcha

**Pull request closed without merging**
